filebeat.inputs:
  - type: log
    paths:
      - /logs/producer/*.log
      - /logs/consumer/*.log
    fields:
      service: java-app
      environment: development
    fields_under_root: true
    scan_frequency: 10s
    multiline:
      pattern: '^\['
      negate: true
      match: after

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~